POST http://localhost:3003/user/signup
Content-Type: application/json

{
	"name": "Luiao",
	"email": "luiao@dundermifflin.com",
	"password": "luiao123456789",
	"role": "NORMAL"
}
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViODcxMmU0LWMwNWUtNGFhMC05YzIzLWZiZDQ0MWEwN2M5OCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzIxNTk2MiwiZXhwIjoxNjU3MjE4OTYyfQ.LS4Irop8OQjoyNbIaV3OY2pG2QGHpX2DD9kCMynjyKA
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
	"email": "ryanhoward@dundermifflin.com",
	"password": "realboss"
}

###
GET http://localhost:3003/user/all
Authorization: {{token}}

###
DELETE http://localhost:3003/user/0c0b8aa8-c73c-4fd9-88ba-4e7296182d1a
Authorization: {{token}}