POST http://localhost:3003/product/create
Content-Type: application/json

{
    "name": "VESTIDO TRICOT CHEVRON",
    "tags": "balada, neutro, delicado, festa"
}

###
GET http://localhost:3003/product/all